/* Simulation code for ThreeWheelVehicle3FMU generated by the OpenModelica Compiler OpenModelica v1.21.0 (64-bit). */
#if !defined(ThreeWheelVehicle3FMU__MODEL_H)
#define ThreeWheelVehicle3FMU__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "ThreeWheelVehicle3FMU_functions.h"

#define Modelica_Math_Vectors_length_index 0
#define Modelica_Math_Vectors_normalize_index 1
#define Modelica_Mechanics_MultiBody_Frames_Orientation_index 2
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_from__nxy_index 3
#define PlanarMechanics_Utilities_Functions_limitBySform_index 4
#define PlanarMechanics_Utilities_Functions_limitByStriple_index 5

extern void ThreeWheelVehicle3FMU_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void ThreeWheelVehicle3FMU_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void ThreeWheelVehicle3FMU_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int ThreeWheelVehicle3FMU_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_checkForAsserts(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int ThreeWheelVehicle3FMU_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* ThreeWheelVehicle3FMU_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* ThreeWheelVehicle3FMU_relationDescription(int i);
extern void ThreeWheelVehicle3FMU_function_initSample(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ThreeWheelVehicle3FMU_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ThreeWheelVehicle3FMU_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* ThreeWheelVehicle3FMU_linear_model_frame(void);
extern const char* ThreeWheelVehicle3FMU_linear_model_datarecovery_frame(void);
extern int ThreeWheelVehicle3FMU_mayer(DATA* data, modelica_real** res, short *);
extern int ThreeWheelVehicle3FMU_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int ThreeWheelVehicle3FMU_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int ThreeWheelVehicle3FMU_setInputData(DATA *data, const modelica_boolean file);
extern int ThreeWheelVehicle3FMU_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void ThreeWheelVehicle3FMU_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void ThreeWheelVehicle3FMU_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int ThreeWheelVehicle3FMU_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void ThreeWheelVehicle3FMU_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void ThreeWheelVehicle3FMU_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int ThreeWheelVehicle3FMU_inputNames(DATA* data, char ** names);
extern int ThreeWheelVehicle3FMU_dataReconciliationInputNames(DATA* data, char ** names);
extern int ThreeWheelVehicle3FMU_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int ThreeWheelVehicle3FMU_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int ThreeWheelVehicle3FMU_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int ThreeWheelVehicle3FMU_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "ThreeWheelVehicle3FMU_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(ThreeWheelVehicle3FMU__MODEL_H) */


